[book]
authors = ["Alex Lai"]
multilingual = true
src = "md"
title = "Developers' Guide"
description = "Guide book for developers' design and progress"


[build]
build-dir = "book"
create-missing = true

# [output.html]
# git_repository_url = "https://github.com/alexlai97/Pitch-Perfectly-Accurately-Practice"
# git_repository_icon = "fa-github"
